### PR TITLE
Add support for elixir 1.7 and distillery 2.x

### PR DESCRIPTION
**Pull request by mobileoverlord**
This PR adds support for elixir 1.7.x and distillery 2.x

### CODE REVIEW

**Comment by mobileoverlord** [comment]
Oh weird, I saw the `:wx` thing before, but I thought it was fixed in distillery since i didn't see it in my new testing.

**Comment by ConnorRigby** [comment]
Ah maybe i have the wrong version of distillery? I think i added `{:distillery, "~> 2.0"}` manually

**Comment by ConnorRigby** [comment]
just removed my manual dep on distillery and updated `nerves` and `shoehorn` same issue.

**Comment by ConnorRigby** [comment]
FWIW i'm testing on [Farmbot OS](https://github.com/FarmBot/farmbot_os/tree/elixir-1.7)

**Comment by mobileoverlord** [comment]
I created a new test project and I was unable to reproduce this issue again, so I tried to compile farmbot os and ran into an issue compiling the source code for the arduino part.

```
Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

make -f c_src/build_calendar/Makefile all ERL_EI_INCLUDE_DIR=/Users/jschneck/.asdf/installs/erlang/21.0.4/usr/include ERL_EI_LIBDIR=/Users/jschneck/.asdf/installs/erlang/21.0.4/usr/lib
make[1]: Nothing to be done for `all'.
cd c_src/farmbot-arduino-firmware && make all BUILD_DIR=/Users/jschneck/Developer/farmbot_os/_build FBARDUINO_FIRMWARE_SRC_DIR=/Users/jschneck/Developer/farmbot_os/c_src/farmbot-arduino-firmware/src BIN_DIR=/Users/jschneck/Developer/farmbot_os/priv
make[1]: *** No rule to make target `all'.  Stop.
make: *** [fbos_arduino_firmware] Error 2
```

**Comment by mobileoverlord** [comment]
I used my 👀 and saw I could skip the arduino build. I get the error now.

**Pull request merged**
